import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { getTrendingMovies } from './api/movies'

function Home({ movies }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the movies
        </h1>

        <ul>
          {movies.map(movie => {
            return (
              <div key={movie.id}>
                <Image className={styles.image} src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`} alt={movie.title} width={75} height={100} />
                <h2>{movie.title}</h2>
                <p>{movie.overview}</p>
              </div>
            )
          })}
        </ul>
      </main>
      <footer></footer>
    </div>
  )
}

export async function getStaticProps() {
  const movies = await getTrendingMovies()
  return {
    props: {
      movies
    }
  }
}

export default Home
